export enum PurchaselyStore {
  AMAZON_APP_STORE = "AMAZON_APP_STORE",
  APPLE_APP_STORE = "APPLE_APP_STORE",
  GOOGLE_PLAY_STORE = "GOOGLE_PLAY_STORE",
  HUAWEI_APP_GALLERY = "HUAWEI_APP_GALLERY",
}
