export enum PurchaselySubscriptionStatus {
  AUTO_RENEWING = "AUTO_RENEWING",
  ON_HOLD = "ON_HOLD",
  IN_GRACE_PERIOD = "IN_GRACE_PERIOD",
  AUTO_RENEWING_CANCELED = "AUTO_RENEWING_CANCELED",
  DEACTIVATED = "DEACTIVATED",
  REVOKED = "REVOKED",
  PAUSED = "PAUSED",
}