export enum PurchaselyProductPlanType {
  CONSUMABLE = "CONSUMABLE",
  NON_CONSUMABLE = "NON_CONSUMABLE",
  NON_RENEWING_SUBSCRIPTION = "NON_RENEWING_SUBSCRIPTION",
  RENEWING_SUBSCRIPTION = "RENEWING_SUBSCRIPTION",
}
