export enum PurchaselyEventName {
  PURCHASE_VALIDATED = "PURCHASE_VALIDATED",
  RENEWAL_DISABLED = "RENEWAL_DISABLED",
  RENEWAL_ENABLED = "RENEWAL_ENABLED",
  SUBSCRIPTION_CHANGED = "SUBSCRIPTION_CHANGED",
  SUBSCRIPTION_EXPIRED = "SUBSCRIPTION_EXPIRED",
  SUBSCRIPTION_RENEWED = "SUBSCRIPTION_RENEWED",
  SUBSCRIPTION_UNPAID = "SUBSCRIPTION_UNPAID",
  TRIAL_CONVERTED = "TRIAL_CONVERTED",
  TRIAL_NOT_CONVERTED = "TRIAL_NOT_CONVERTED",
  TRIAL_STARTED = "TRIAL_STARTED",
}
