name: Deploy On New Version Tag
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Node Version
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Cache Yarn Dependencies
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install Firebase
        run: |
          yarn install
          yarn global add firebase-tools
      - name: Install Dependencies
        run: |
          cd ./functions
          yarn install
          cd ../
      - name: Build
        run: |
          cd ./functions
          tsc --build tsconfig.json
          cd ../
      - name: Archive Extension Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: latest-production-artifact
          retention-days: 30
          path: |
            auto-extension-install.exp
            auto-extension-update.exp
            extension.yaml
            firebase.json
            package.json
            POSTINSTALL.md
            PREINSTALL.md
            functions/src
            functions/__tests__
            functions/lib
            functions/tsconfig.json
            functions/package.json
            functions/yarn.lock
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Node Version
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Download Build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: latest-production-artifact
      - name: Cache Yarn Dependencies
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install Firebase
        run: |
          yarn install
          yarn global add firebase-tools
      - name: Install Dependencies
        run: |
          cd ./functions
          yarn install
          cd ../
      - name: Run tests with mocks
        run: |
          firebase emulators:start --only firestore &
          cd ./functions
          yarn run test
          cd ../
        env:
          FIRESTORE_EMULATOR_HOST: "localhost:8080"
      - name: Archive Extension Coverage
        uses: actions/upload-artifact@v2
        with:
          name: latest-production-coverage
          retention-days: 30
          path: |
            functions/coverage
  coverage:
    name: Upload Coverage
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download Test Coverage Artifacts
        uses: actions/download-artifact@v2
        with:
          name: latest-production-coverage
      - name: Archive Extension Coverage
        run: echo "Upload the extension's test coverage"
  publish:
    name: Publish (STAND-IN; TO BE IMPLEMENTED)
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: latest-production-artifact
      - name: Cache Yarn Dependencies
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Setup Node Version
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install Firebase
        run: |
          yarn install
          yarn global add firebase-tools
      - name: Install Expect
        run: sudo apt-get install expect
      - name: Install Dependencies
        run: |
          cd ./functions
          yarn install
          cd ../
      - name: Export Client Webhook Shared Secret to Extension Params File
        env:
          PURCHASELY_SHARED_SECRET: ${{ secrets.PURCHASELY_SHARED_SECRET }}
        run: |
          echo PURCHASELY_SHARED_SECRET=$PURCHASELY_SHARED_SECRET >> .extension-params.env
          cat .extension-params.env
      - name: Publish
        run: |
          echo "PUBLISHING THE FIREBASE EXTENSION UPDATE"
          yarn run firebase ext:dev:publish purchasely/purchasely-in-app-purchases --token $(FIREBASE_TOKEN) --non-interactive --force
          echo "PUBLISHED THE FIREBASE EXTENSION UPDATE"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
