name: Deploy On New Version Tag
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Node Version
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Cache Yarn Dependencies
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install Firebase
        run: |
          yarn install
      - name: Install Dependencies
        run: |
          cd ./functions
          yarn install
          cd ../
      - name: Build
        run: |
          cd ./functions
          tsc --build tsconfig.json
          cd ../
      - name: Archive Extension Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: latest-production-artifact
          retention-days: 30
          path: |
            extension.yaml
            firebase.json
            package.json
            CHANGELOG.md
            POSTINSTALL.md
            PREINSTALL.md
            functions/src
            functions/__tests__
            functions/lib
            functions/tsconfig.json
            functions/package.json
            functions/yarn.lock
            ci
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Node Version
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: latest-production-artifact
      - name: Cache Yarn Dependencies
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install Firebase
        run: |
          yarn install
          yarn global add firebase-tools@v12.5.2
      - name: Install Dependencies
        run: |
          cd ./functions
          yarn install
          cd ../
      - name: Run tests with mocks
        run: |
          firebase emulators:exec --only firestore "cd ./functions && yarn test && cd ../"
        env:
          FIRESTORE_EMULATOR_HOST: "localhost:8080"
      - name: Archive Extension Coverage
        uses: actions/upload-artifact@v3
        with:
          name: latest-production-coverage
          retention-days: 30
          path: |
            functions/coverage
  coverage:
    name: Upload Coverage
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download Test Coverage Artifacts
        uses: actions/download-artifact@v3
        with:
          name: latest-production-coverage
      - name: Archive Extension Coverage
        run: echo "Upload the extension's test coverage"
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: latest-production-artifact
      - name: Cache Yarn Dependencies
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Setup Node Version
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install Firebase
        run: |
          yarn install
          yarn global add firebase-tools@v12.5.2
      - name: Install Dependencies
        run: |
          cd ./functions
          yarn install
          cd ../
      - name: Publish
        run: |
          echo "PUBLISHING THE FIREBASE EXTENSION UPDATE"
          firebase ext:dev:upload purchasely/purchasely-in-app-purchases --token $FIREBASE_TOKEN
          # firebase --open-sesame extdev
          # firebase ext:dev:publish purchasely/purchasely-in-app-purchases --token $FIREBASE_TOKEN --project $PROJECT_ID --non-interactive --force
          echo "PUBLISHED THE FIREBASE EXTENSION UPDATE"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
